name: CI

on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Setup
      run: |
        sudo apt-get -yqq install libpq-dev
        gem install bundler
    - name: Install
      run: bundle install --jobs 4 --retry 3
    - name: Test
      run: rspec
    - name: Lint
      run: rubocop